runtime: python313 # Define the Python version
entrypoint: gunicorn -b :$PORT main:app  # Define how to start the app

handlers:
  - url: /static
    static_dir: static  # Serve static files from the "static" folder

  - url: /.*
    script: auto  # Directs all other traffic to the main application

env_variables:
  SECRET_KEY: "your-secret-key"
  DATABASE_URL: "your-database-url"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5
